#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from 1605106.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "1605106.y"

#include<iostream>
#include<cstdlib>
#include<cstring>
#include<cmath>
#include<cstdio>
#include<vector>
#include "1605106_SymbolTable.h"
using namespace std;
int yyparse(void);
extern "C" int yylex(void);
extern FILE *yyin;
vector<SymbolInfo*> parameters;
vector<SymbolInfo*> declarations;
vector<SymbolInfo*> arguments;
FILE *parser = fopen("1605106_parser.txt", "w");
FILE *errorFile = fopen("1605106_error.txt", "w");
FILE *fp;
SymbolTable *myTable = new SymbolTable(7);
int lines = 1;
int errors = 0;

void yyerror(char *s){cerr << "Line no" << lines << endl;}


#line 41 "1605106.y"
typedef union
{
    SymbolInfo* var;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	ELSE	259
#define	FOR	260
#define	WHILE	261
#define	DO	262
#define	BREAK	263
#define	INT	264
#define	CHAR	265
#define	FLOAT	266
#define	DOUBLE	267
#define	VOID	268
#define	RETURN	269
#define	SWITCH	270
#define	CASE	271
#define	DEFAULT	272
#define	CONTINUE	273
#define	ADDOP	274
#define	MULOP	275
#define	INCOP	276
#define	RELOP	277
#define	ASSIGNOP	278
#define	LOGICOP	279
#define	BITOP	280
#define	NOT	281
#define	COMMA	282
#define	SEMICOLON	283
#define	LPAREN	284
#define	LCURL	285
#define	LTHIRD	286
#define	RPAREN	287
#define	RCURL	288
#define	RTHIRD	289
#define	CONST_INT	290
#define	CONST_FLOAT	291
#define	CONST_CHAR	292
#define	CONST_STRING	293
#define	ID	294
#define	PRINTLN	295
#define	DECOP	296
#define	AFTER_ELSE	297


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int ELSE;
static const int FOR;
static const int WHILE;
static const int DO;
static const int BREAK;
static const int INT;
static const int CHAR;
static const int FLOAT;
static const int DOUBLE;
static const int VOID;
static const int RETURN;
static const int SWITCH;
static const int CASE;
static const int DEFAULT;
static const int CONTINUE;
static const int ADDOP;
static const int MULOP;
static const int INCOP;
static const int RELOP;
static const int ASSIGNOP;
static const int LOGICOP;
static const int BITOP;
static const int NOT;
static const int COMMA;
static const int SEMICOLON;
static const int LPAREN;
static const int LCURL;
static const int LTHIRD;
static const int RPAREN;
static const int RCURL;
static const int RTHIRD;
static const int CONST_INT;
static const int CONST_FLOAT;
static const int CONST_CHAR;
static const int CONST_STRING;
static const int ID;
static const int PRINTLN;
static const int DECOP;
static const int AFTER_ELSE;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,ELSE=259
	,FOR=260
	,WHILE=261
	,DO=262
	,BREAK=263
	,INT=264
	,CHAR=265
	,FLOAT=266
	,DOUBLE=267
	,VOID=268
	,RETURN=269
	,SWITCH=270
	,CASE=271
	,DEFAULT=272
	,CONTINUE=273
	,ADDOP=274
	,MULOP=275
	,INCOP=276
	,RELOP=277
	,ASSIGNOP=278
	,LOGICOP=279
	,BITOP=280
	,NOT=281
	,COMMA=282
	,SEMICOLON=283
	,LPAREN=284
	,LCURL=285
	,LTHIRD=286
	,RPAREN=287
	,RCURL=288
	,RTHIRD=289
	,CONST_INT=290
	,CONST_FLOAT=291
	,CONST_CHAR=292
	,CONST_STRING=293
	,ID=294
	,PRINTLN=295
	,DECOP=296
	,AFTER_ELSE=297


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::ELSE=259;
const int YY_parse_CLASS::FOR=260;
const int YY_parse_CLASS::WHILE=261;
const int YY_parse_CLASS::DO=262;
const int YY_parse_CLASS::BREAK=263;
const int YY_parse_CLASS::INT=264;
const int YY_parse_CLASS::CHAR=265;
const int YY_parse_CLASS::FLOAT=266;
const int YY_parse_CLASS::DOUBLE=267;
const int YY_parse_CLASS::VOID=268;
const int YY_parse_CLASS::RETURN=269;
const int YY_parse_CLASS::SWITCH=270;
const int YY_parse_CLASS::CASE=271;
const int YY_parse_CLASS::DEFAULT=272;
const int YY_parse_CLASS::CONTINUE=273;
const int YY_parse_CLASS::ADDOP=274;
const int YY_parse_CLASS::MULOP=275;
const int YY_parse_CLASS::INCOP=276;
const int YY_parse_CLASS::RELOP=277;
const int YY_parse_CLASS::ASSIGNOP=278;
const int YY_parse_CLASS::LOGICOP=279;
const int YY_parse_CLASS::BITOP=280;
const int YY_parse_CLASS::NOT=281;
const int YY_parse_CLASS::COMMA=282;
const int YY_parse_CLASS::SEMICOLON=283;
const int YY_parse_CLASS::LPAREN=284;
const int YY_parse_CLASS::LCURL=285;
const int YY_parse_CLASS::LTHIRD=286;
const int YY_parse_CLASS::RPAREN=287;
const int YY_parse_CLASS::RCURL=288;
const int YY_parse_CLASS::RTHIRD=289;
const int YY_parse_CLASS::CONST_INT=290;
const int YY_parse_CLASS::CONST_FLOAT=291;
const int YY_parse_CLASS::CONST_CHAR=292;
const int YY_parse_CLASS::CONST_STRING=293;
const int YY_parse_CLASS::ID=294;
const int YY_parse_CLASS::PRINTLN=295;
const int YY_parse_CLASS::DECOP=296;
const int YY_parse_CLASS::AFTER_ELSE=297;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		121
#define	YYFLAG		-32768
#define	YYNTBASE	43

#define YYTRANSLATE(x) ((unsigned)(x) <= 297 ? yytranslate[x] : 69)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     9,    11,    13,    20,    26,    27,
    35,    36,    43,    48,    52,    55,    57,    58,    63,    66,
    70,    72,    74,    76,    80,    87,    89,    94,    96,    99,
   101,   103,   105,   113,   119,   127,   133,   139,   143,   145,
   148,   150,   155,   157,   161,   163,   167,   169,   173,   175,
   179,   181,   185,   188,   191,   193,   195,   200,   204,   206,
   208,   211,   214,   216,   217,   221
};

static const short yyrhs[] = {    44,
     0,    44,    45,     0,    45,     0,    53,     0,    46,     0,
    47,     0,    54,    39,    29,    50,    32,    28,     0,    54,
    39,    29,    32,    28,     0,     0,    54,    39,    29,    50,
    32,    48,    51,     0,     0,    54,    39,    29,    32,    49,
    51,     0,    50,    27,    54,    39,     0,    50,    27,    54,
     0,    54,    39,     0,    54,     0,     0,    30,    52,    56,
    33,     0,    30,    33,     0,    54,    55,    28,     0,     9,
     0,    11,     0,    13,     0,    55,    27,    39,     0,    55,
    27,    39,    31,    35,    34,     0,    39,     0,    39,    31,
    35,    34,     0,    57,     0,    56,    57,     0,    53,     0,
    58,     0,    51,     0,     5,    29,    58,    58,    60,    32,
    57,     0,     3,    29,    60,    32,    57,     0,     3,    29,
    60,    32,    57,     4,    57,     0,     6,    29,    60,    32,
    57,     0,    40,    29,    39,    32,    28,     0,    14,    60,
    28,     0,    28,     0,    60,    28,     0,    39,     0,    39,
    31,    60,    34,     0,    61,     0,    59,    23,    61,     0,
    62,     0,    62,    24,    62,     0,    63,     0,    63,    22,
    63,     0,    64,     0,    63,    19,    64,     0,    65,     0,
    64,    20,    65,     0,    19,    65,     0,    26,    65,     0,
    66,     0,    59,     0,    39,    29,    67,    32,     0,    29,
    60,    32,     0,    35,     0,    36,     0,    59,    21,     0,
    59,    41,     0,    68,     0,     0,    68,    27,    61,     0,
    61,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    49,    53,    57,    63,    69,    75,    81,   132,   180,   240,
   247,   283,   293,   302,   313,   323,   336,   343,   354,   374,
   413,   420,   427,   436,   446,   457,   467,   479,   488,   499,
   508,   517,   526,   542,   556,   572,   586,   595,   616,   625,
   636,   664,   713,   722,   754,   764,   786,   795,   814,   824,
   846,   856,   907,   934,   957,   967,   976,  1026,  1035,  1044,
  1053,  1062,  1074,  1081,  1088,  1096
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","ELSE",
"FOR","WHILE","DO","BREAK","INT","CHAR","FLOAT","DOUBLE","VOID","RETURN","SWITCH",
"CASE","DEFAULT","CONTINUE","ADDOP","MULOP","INCOP","RELOP","ASSIGNOP","LOGICOP",
"BITOP","NOT","COMMA","SEMICOLON","LPAREN","LCURL","LTHIRD","RPAREN","RCURL",
"RTHIRD","CONST_INT","CONST_FLOAT","CONST_CHAR","CONST_STRING","ID","PRINTLN",
"DECOP","AFTER_ELSE","start","program","unit","func_declaration","func_definition",
"@1","@2","parameter_list","compound_statement","@3","var_declaration","type_specifier",
"declaration_list","statements","statement","expression_statement","variable",
"expression","logic_expression","rel_expression","simple_expression","term",
"unary_expression","factor","argument_list","arguments",""
};
#endif

static const short yyr1[] = {     0,
    43,    44,    44,    45,    45,    45,    46,    46,    48,    47,
    49,    47,    50,    50,    50,    50,    52,    51,    51,    53,
    54,    54,    54,    55,    55,    55,    55,    56,    56,    57,
    57,    57,    57,    57,    57,    57,    57,    57,    58,    58,
    59,    59,    60,    60,    61,    61,    62,    62,    63,    63,
    64,    64,    65,    65,    65,    66,    66,    66,    66,    66,
    66,    66,    67,    67,    68,    68
};

static const short yyr2[] = {     0,
     1,     2,     1,     1,     1,     1,     6,     5,     0,     7,
     0,     6,     4,     3,     2,     1,     0,     4,     2,     3,
     1,     1,     1,     3,     6,     1,     4,     1,     2,     1,
     1,     1,     7,     5,     7,     5,     5,     3,     1,     2,
     1,     4,     1,     3,     1,     3,     1,     3,     1,     3,
     1,     3,     2,     2,     1,     1,     4,     3,     1,     1,
     2,     2,     1,     0,     3,     1
};

static const short yydefact[] = {     0,
    21,    22,    23,     1,     3,     5,     6,     4,     0,     2,
    26,     0,     0,     0,     0,    20,    11,     0,    16,     0,
    24,     8,     0,     0,     9,    15,    27,     0,    17,    12,
    14,     7,     0,     0,    19,     0,    13,    10,    25,     0,
     0,     0,     0,     0,     0,    39,     0,    59,    60,    41,
     0,    32,    30,     0,     0,    28,    31,    56,     0,    43,
    45,    47,    49,    51,    55,     0,     0,     0,     0,    56,
    53,    54,     0,    64,     0,     0,    26,    18,    29,    61,
     0,    62,    40,     0,     0,     0,     0,     0,     0,     0,
    38,    58,    66,     0,    63,     0,     0,    44,    46,    50,
    48,    52,     0,     0,     0,    57,     0,    42,     0,    34,
     0,    36,    65,    37,     0,     0,    35,    33,     0,     0,
     0
};

static const short yydefgoto[] = {   119,
     4,     5,     6,     7,    33,    23,    18,    52,    36,    53,
    54,    12,    55,    56,    57,    58,    59,    60,    61,    62,
    63,    64,    65,    94,    95
};

static const short yypact[] = {    93,
-32768,-32768,-32768,    93,-32768,-32768,-32768,-32768,   -35,-32768,
    30,    47,     6,   -14,   -12,-32768,     4,    -7,    11,    24,
    14,-32768,    37,    93,    32,-32768,-32768,    42,    52,-32768,
    41,-32768,    37,    55,-32768,    81,-32768,-32768,-32768,    64,
    67,    70,    62,    62,    62,-32768,    62,-32768,-32768,    39,
    74,-32768,-32768,    66,    43,-32768,-32768,    -5,    80,-32768,
    88,    25,    94,-32768,-32768,    62,    96,    62,    85,   -10,
-32768,-32768,    86,    62,    62,    84,    95,-32768,-32768,-32768,
    62,-32768,-32768,    62,    62,    62,    62,    87,    96,    97,
-32768,-32768,-32768,    98,   100,    99,   102,-32768,-32768,    94,
   109,-32768,    81,    62,    81,-32768,    62,-32768,   108,   133,
   106,-32768,-32768,-32768,    81,    81,-32768,-32768,   139,   140,
-32768
};

static const short yypgoto[] = {-32768,
-32768,   137,-32768,-32768,-32768,-32768,-32768,   -11,-32768,    29,
    10,-32768,-32768,   -50,   -65,   -44,   -40,   -68,    58,    57,
    59,   -36,-32768,-32768,-32768
};


#define	YYLAST		144


static const short yytable[] = {    70,
    70,    89,    69,    11,    79,    93,    73,    71,    72,     9,
    80,    30,    98,     9,     1,    80,     2,    81,     3,    24,
    20,    38,    19,   104,    25,    88,    21,    90,     8,    70,
    82,    22,     8,    31,    96,    82,    70,    17,   113,    70,
    70,    70,    70,    85,    28,    40,    86,    41,    42,    26,
   102,     1,   110,     2,   112,     3,    43,    27,    13,    32,
    14,    44,    70,   111,   117,   118,    29,    74,    45,    75,
    46,    47,    29,    15,    16,    78,    34,    48,    49,    37,
    44,    50,    51,    40,    35,    41,    42,    45,    39,     1,
    47,     2,    66,     3,    43,    67,    48,    49,    68,    44,
    50,     1,    76,     2,    77,     3,    45,    83,    46,    47,
    29,    84,    91,    87,    44,    48,    49,    92,   103,    50,
    51,    45,    97,    46,    47,    14,   107,    85,   105,   106,
    48,    49,   108,   109,    50,   114,   115,   116,   120,   121,
    10,    99,   101,   100
};

static const short yycheck[] = {    44,
    45,    67,    43,    39,    55,    74,    47,    44,    45,     0,
    21,    23,    81,     4,     9,    21,    11,    23,    13,    27,
    35,    33,    13,    89,    32,    66,    39,    68,     0,    74,
    41,    28,     4,    24,    75,    41,    81,    32,   107,    84,
    85,    86,    87,    19,    31,     3,    22,     5,     6,    39,
    87,     9,   103,    11,   105,    13,    14,    34,    29,    28,
    31,    19,   107,   104,   115,   116,    30,    29,    26,    31,
    28,    29,    30,    27,    28,    33,    35,    35,    36,    39,
    19,    39,    40,     3,    33,     5,     6,    26,    34,     9,
    29,    11,    29,    13,    14,    29,    35,    36,    29,    19,
    39,     9,    29,    11,    39,    13,    26,    28,    28,    29,
    30,    24,    28,    20,    19,    35,    36,    32,    32,    39,
    40,    26,    39,    28,    29,    31,    27,    19,    32,    32,
    35,    36,    34,    32,    39,    28,     4,    32,     0,     0,
     4,    84,    86,    85
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 49 "1605106.y"
{ 
;
    break;}
case 2:
#line 53 "1605106.y"
{
	fprintf(parser, "At line no : %d program : program unit\n\n", lines);
	yyval.var = new SymbolInfo(); yyval.var -> setName(yyvsp[-1].var -> getName() + yyvsp[0].var -> getName()); fprintf(parser, "%s %s\n\n", yyvsp[-1].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
;
    break;}
case 3:
#line 57 "1605106.y"
{
	fprintf(parser, "At line no : %d program : unit\n\n", lines);
	yyval.var = new SymbolInfo(); yyval.var -> setName(yyvsp[0].var -> getName()); fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
;
    break;}
case 4:
#line 63 "1605106.y"
{ 
	fprintf(parser, "At line no : %d unit : var_declaration\n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName(yyvsp[0].var -> getName()+"\n");fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 5:
#line 69 "1605106.y"
{
	fprintf(parser, "At line no : %d unit : func_declaration\n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName(yyvsp[0].var -> getName() + "\n"); fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 6:
#line 75 "1605106.y"
{
	fprintf(parser, "At line no : %d unit : func_definition\n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName(yyvsp[0].var -> getName() + "\n"); fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
;
    break;}
case 7:
#line 81 "1605106.y"
{
	fprintf(parser, "At line no : %d func_declaration : type_specifier ID LPAREN parameter_list RPAREN SEMICOLON\n\n", lines);
	yyval.var = new SymbolInfo();
	string variableName = yyvsp[-4].var->getName();
	fprintf(parser, "%s %s(%s);\n\n", yyvsp[-5].var -> getName().c_str(), yyvsp[-4].var -> getName().c_str(), yyvsp[-2].var -> getName().c_str());
	SymbolInfo *temp = myTable->lookUp(variableName);
	if(temp != 0){
		//cout << "Check totalparameter " << temp -> getFunction() -> getTotalParameters() << endl;
		if(temp -> getFunction() -> getTotalParameters() != parameters.size()){
			vector<string>pType = temp -> getFunction()-> getParameterType();
			int limit = parameters.size();
			for(int i=0; i < limit; i++) {
				string decI = parameters[i] -> getDeclaration(); 
				if(decI != pType[i]){
					fprintf(errorFile, "Error at Line %d : Type Mismatch \n\n",lines);
					errors++;
					break;
				}
			}
			string returnType = temp->getFunction() -> getRType();
			if(returnType != yyvsp[-5].var -> getName()){
				fprintf(errorFile,"Error at Line %d : Return Type Mismatch \n\n",lines);
				errors++;
			}
			parameters.clear();
		}
		else {
			fprintf(errorFile, "Error at Line %d : Parameter size doesn't match \n\n",lines);
			errors++;
		}

	}
	else{
		string name2 = yyvsp[-4].var -> getName();
		myTable->insert(yyvsp[-4].var->getName(), "ID", "Function");
		temp = myTable -> lookUp(name2);
		temp -> setFunction();
		int limit = parameters.size();
		for(int i=0; i<limit; i++){
			string paramName = parameters[i]->getName();
			string paramDec = parameters[i]->getDeclaration();
			temp -> getFunction() -> addParameter(paramName, paramDec);
		}
		//cout << "Check size " << parameters.size()<< endl;
		parameters.clear();
		string n = yyvsp[-5].var->getName();
		temp -> getFunction() -> setRType(n);
	}
	string var1 = yyvsp[-5].var -> getName();  string var2 = yyvsp[-4].var -> getName(); string var4 = yyvsp[-2].var -> getName();
	yyval.var -> setName(var1 + var2 + "(" + var4 + ")" + ";");
;
    break;}
case 8:
#line 132 "1605106.y"
{
	fprintf(parser, "At line no : %d func_declaration : type_specifier ID LPAREN RPAREN SEMICOLON\n\n", lines);
	fprintf(parser, "%s %s();\n\n", yyvsp[-4].var -> getName().c_str(), yyvsp[-3].var -> getName().c_str());
	
	yyval.var = new SymbolInfo();
	
	SymbolInfo* temp = myTable -> lookUp(yyvsp[-3].var -> getName());
	
	if(temp != 0){
		int total = temp -> getFunction() -> getTotalParameters();
		if(total != 0){
			
			fprintf(errorFile,"Error at Line %d : Invalid number of parameters \n\n",lines);


			errors++;
		}

		string returnType = temp->getFunction() -> getRType();

		if(returnType != yyvsp[-4].var -> getName()){
			
			fprintf(errorFile,"Error at Line %d : Return Type Mismatch \n\n",lines);



			errors++;
		}
		


		
	}
	else{
		string var2Name = yyvsp[-3].var->getName();
		myTable->insert(var2Name, "ID", "Function");
		temp = myTable -> lookUp(var2Name);
		string var1Name = yyvsp[-4].var->getName();
		temp -> setFunction(); //this creates the function for temp
		//now the function must have a return type
		temp -> getFunction() -> setRType(var1Name);
	}
	string name1 = yyvsp[-4].var -> getName();
	string name2 = yyvsp[-3].var -> getName();
	string extra = "();";
	yyval.var -> setName(name1 + name2 + extra);
;
    break;}
case 9:
#line 180 "1605106.y"
{
	yyval.var = new SymbolInfo();
	string name2 = yyvsp[-3].var->getName();
	SymbolInfo *temp = myTable->lookUp(name2);
	if(temp != 0){
		bool def = temp->getFunction()->getDefined();
		if(def != 0){
			fprintf(errorFile,"Error at Line %d : Multiple definition of Function %s\n\n",lines, yyvsp[-3].var->getName().c_str());
			errors++;
		}
		else {
			if(temp -> getFunction() -> getTotalParameters() != parameters.size()){
				
				fprintf(errorFile,"Error at Line %d : Invalid number of parameters \n\n",lines);

				errors++;
			}
			else {
				vector<string>pType = temp -> getFunction()-> getParameterType();
				int limit = parameters.size();


				for(int i=0; i<limit; i++) {
					//Type Mismatch checking 
					string paramDec = parameters[i] -> getDeclaration();
					if(paramDec != pType[i]){
						fprintf(errorFile, "Error at Line %d : Type Mismatch \n\n",lines);
						errors++;
						break;
					}
				}
				string returnType = temp->getFunction() -> getRType();
				string n1 = yyvsp[-4].var -> getName();
				if(returnType != n1){
					fprintf(errorFile,"Error at Line %d : Return Type Mismatch \n\n",lines);
					errors++;
				}
			}
			//the function must set defined
			temp -> getFunction() -> setDefined();

			
		}
		
	}
	else {
		string name2 = yyvsp[-3].var -> getName();string type = "ID";string dec = "Function";myTable -> insert(name2, type, dec);
		temp = myTable -> lookUp(name2);
		temp -> setFunction();
		temp -> getFunction() -> setDefined();
		int limit = parameters.size();
		string returnType = yyvsp[-4].var -> getName();
		//cout << "LIMIT " << limit << endl;
		for(int i=0; i<limit; i++){ 
			string paramName = parameters[i] -> getName();
			string paramDec = parameters[i] -> getDeclaration();
			temp -> getFunction() -> addParameter(paramName, paramDec);
			}
		temp -> getFunction() -> setRType(returnType);
	}
;
    break;}
case 10:
#line 240 "1605106.y"
{
	fprintf(parser, "At line no : %d func_definition : type_specifier ID LPAREN parameter_list RPAREN compound_statement\n\n", lines);
	fprintf(parser, "%s %s(%s) %s\n\n", yyvsp[-6].var -> getName().c_str(), yyvsp[-5].var -> getName().c_str(), yyvsp[-3].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	string name1 = yyvsp[-6].var -> getName();string name2 = yyvsp[-5].var -> getName();string name4 = yyvsp[-3].var -> getName();string name7 = yyvsp[0].var -> getName(); 
	yyval.var -> setName(name1 + " " + name2 + "(" + name4 + ")" + name7);
	//cout << $<var>1 -> getName() << endl;
;
    break;}
case 11:
#line 247 "1605106.y"
{
	yyval.var = new SymbolInfo();
	string name = yyvsp[-2].var -> getName();
	string name1 = yyvsp[-3].var -> getName();
	SymbolInfo *temp = myTable -> lookUp(name);
	if(temp == 0){
		myTable -> insert(name, "ID", "Function");
		temp = myTable -> lookUp(name);
		temp -> setFunction();
		temp -> getFunction() -> setDefined();
		temp -> getFunction() -> setRType(name1);
	}
	else if(temp -> getFunction() -> getDefined() == 0) {
		int total = temp -> getFunction() -> getTotalParameters();
		string returnType = temp -> getFunction() -> getRType();
		if(total != 0){
			fprintf(errorFile,"Error at Line %d : Invalid number of parameters \n\n",lines);
			errors++;
		}
		if(returnType != yyvsp[-3].var -> getName()){
			fprintf(errorFile,"Error at Line %d : Return Type Mismatch \n\n",lines);
			errors++;
		}
		temp -> getFunction() -> setDefined();
	}

	
	
	else {
		
		fprintf(errorFile,"Error at Line %d : Multiple definition of Function %s\n\n",lines, yyvsp[-2].var->getName().c_str());
		
		
		errors++;
		
		}
;
    break;}
case 12:
#line 283 "1605106.y"
{
	fprintf(parser, "At line no : %d func_definition : type_specifier ID LPAREN RPAREN compound_statement\n", lines);
	fprintf(parser, "%s %s() %s\n\n", yyvsp[-5].var -> getName().c_str(),yyvsp[-4].var -> getName().c_str() ,yyvsp[0].var -> getName().c_str());
	string name1 = yyvsp[-5].var -> getName();
	string name2 = yyvsp[-4].var -> getName();
	string name6 = yyvsp[0].var -> getName();
	yyval.var -> setName(name1 +name2+"()"+ name6);
;
    break;}
case 13:
#line 293 "1605106.y"
{
	fprintf(parser, "At line no : %d parameter_list : parameter_list COMMA type_specifier ID\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[-3].var -> getName() + "," + yyvsp[-1].var -> getName() + " " + yyvsp[0].var -> getName());
	parameters.push_back(new SymbolInfo(yyvsp[0].var -> getName(), "ID", yyvsp[-1].var -> getName()));
	fprintf(parser, "%s,%s %s\n\n", yyvsp[-3].var -> getName().c_str(), yyvsp[-1].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 14:
#line 302 "1605106.y"
{
	fprintf(parser, "At line no : %d parameter_list : parameter_list COMMA type_specifier\n\n", lines);
	yyval.var = new SymbolInfo();
	string var1 = yyvsp[-2].var -> getName();
	string var3 = yyvsp[0].var -> getName();
	yyval.var -> setName(var1 + "," + var3);
	string type = "ID";
	parameters.push_back(new SymbolInfo("",type,var3));
	fprintf(parser, "%s,%s\n\n", yyvsp[-2].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 15:
#line 313 "1605106.y"
{
	fprintf(parser, "At line no : %d parameter_list : type_specifier ID\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[-1].var -> getName() + " " + yyvsp[0].var -> getName());
	parameters.push_back(new SymbolInfo(yyvsp[0].var -> getName(), "ID", yyvsp[-1].var -> getName()));

	fprintf(parser, "%s %s\n\n", yyvsp[-1].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 16:
#line 323 "1605106.y"
{
	fprintf(parser, "At line no : %d parameter_list : type_specifier\n\n", lines);
	yyval.var = new SymbolInfo();


	yyval.var -> setName(yyvsp[0].var -> getName() + " ");
	parameters.push_back(new SymbolInfo("", "ID", yyvsp[2].var -> getName()));

	fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 17:
#line 336 "1605106.y"
{
	myTable -> enterScope(7);
	int limit = parameters.size();
	for(int i=0; i < limit; i++){
		myTable -> insert(parameters[i]->getName(), "ID", parameters[i] -> getDeclaration());
	}
	parameters.clear();
;
    break;}
case 18:
#line 343 "1605106.y"
{
	fprintf(parser, "At line no : %d compound_statement : LCURL statements RCURL\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName("{\n" + yyvsp[-1].var -> getName() + "\n}");

	fprintf(parser, "{\n%s\n}\n\n", yyvsp[-1].var -> getName().c_str());
	
	//myTable -> printAllScopeTables();
	myTable -> exitScope();
;
    break;}
case 19:
#line 354 "1605106.y"
{
	myTable -> enterScope(7);
	int limit = parameters.size();

	for(int i=0; i < limit; i++){
		string dec = parameters[i] -> getDeclaration();
		string name = parameters[i]->getName();
		string type = "ID";
		myTable -> insert(name, type, dec);
	}
	parameters.clear();
	fprintf(parser, "At line no : %d compound_statement : LCURL RCURL\n\n", lines);
	fprintf(parser, "{}\n\n");
	yyval.var = new SymbolInfo();
	yyval.var -> setName("{}");
	//myTable -> printAllScopeTables();
	myTable -> exitScope();
;
    break;}
case 20:
#line 374 "1605106.y"
{
	fprintf(parser, "At line no : %d var_declaration : type_specifier declaration_list SEMICOLON\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "%s %s;\n\n", yyvsp[-2].var->getName().c_str(), yyvsp[-1].var->getName().c_str());
	string name = yyvsp[-2].var -> getName();
	string v = "void ";
	if(name == v){
		fprintf(errorFile,"Error at Line %d : Invalid declaration of variable\n\n",lines);

		errors++;
	}
	else {
		int limit = declarations.size();
		for(int i =0; i < limit; i++){
			if(myTable -> findCurrent(declarations[i]->getName())) {
				fprintf(errorFile,"Error at Line %d : Multiple declaration of variable %s\n\n",lines, declarations[i]->getName().c_str());
				errors++;
				continue;
			}
			int decSize = declarations[i]-> getType().size();
			string decName = declarations[i] -> getName();
			string decType = declarations[i] -> getType();
			if(decSize != 3){
				myTable -> insert(decName, decType, yyvsp[-2].var -> getName());
			}
			else {
				string s = declarations[i] -> getType().substr(0, declarations[i] -> getType().size()-1);
				declarations[i] -> setType(s);
				myTable -> insert(decName, decType, yyvsp[-2].var -> getName()+"array");
			}
		}
	}
	string name1 = yyvsp[-2].var -> getName();
	string name2 = yyvsp[-1].var -> getName();
	declarations.clear();
	yyval.var -> setName(name1 + " " + name2 + ";");
;
    break;}
case 21:
#line 413 "1605106.y"
{
	fprintf(parser, "At line no : %d type_specifier : INT\n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName("int ");
	fprintf(parser, "int \n\n");
	
;
    break;}
case 22:
#line 420 "1605106.y"
{
	fprintf(parser, "At line no : %d type_specifier : FLOAT\n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName("float ");
	fprintf(parser, "float \n\n");
	
;
    break;}
case 23:
#line 427 "1605106.y"
{
	fprintf(parser, "At line no : %d type_specifier : VOID \n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName("void ");
	fprintf(parser, "void \n\n");
	
;
    break;}
case 24:
#line 436 "1605106.y"
{
	fprintf(parser, "At line no : %d declaration_list : declaration_list COMMA ID\n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName(yyvsp[-2].var -> getName() + "," + yyvsp[0].var -> getName());
	fprintf(parser, "%s,%s\n\n", yyvsp[-2].var->getName().c_str(), yyvsp[0].var->getName().c_str());
	string  n3 = yyvsp[0].var -> getName();
	string type =  "ID";
	declarations.push_back(new SymbolInfo(n3, type));
	
;
    break;}
case 25:
#line 446 "1605106.y"
{
	fprintf(parser, "At line no : %d declaration_list : declaration_list COMMA ID LTHIRD CONST_INT RTHIRD\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[-5].var -> getName() + "," + yyvsp[-3].var -> getName() + "[" + yyvsp[-1].var -> getName() + "]");
	string  n3 = yyvsp[-3].var -> getName();
	string type =  "IDa";
	fprintf(parser, "%s,%s[%s]\n\n", yyvsp[-5].var -> getName().c_str(), yyvsp[-3].var -> getName().c_str(), yyvsp[-1].var -> getName().c_str());
	declarations.push_back(new SymbolInfo(n3,type));
	
;
    break;}
case 26:
#line 457 "1605106.y"
{
	fprintf(parser, "At line no : %d declaration_list : ID\n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName(yyvsp[0].var -> getName());
	fprintf(parser, "%s\n\n", yyvsp[0].var->getName().c_str());
	string  n1 = yyvsp[0].var -> getName();
	string type =  "ID";
	declarations.push_back(new SymbolInfo(n1, type));
	
;
    break;}
case 27:
#line 467 "1605106.y"
{
	fprintf(parser, "At line no : %d declaration_list : ID LTHIRD CONST_INT RTHIRD\n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName(yyvsp[-3].var -> getName() + "[" + yyvsp[-1].var -> getName() + "]");
	fprintf(parser, "%s[%s]\n\n", yyvsp[-3].var -> getName().c_str(), yyvsp[-1].var -> getName().c_str());
	string  n1 = yyvsp[-3].var -> getName();
	string type =  "IDa";
	declarations.push_back(new SymbolInfo(n1, type));
	
;
    break;}
case 28:
#line 479 "1605106.y"
{
	fprintf(parser, "At line no : %d statements : statement\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[0].var -> getName());

	fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());	
	
;
    break;}
case 29:
#line 488 "1605106.y"
{
	fprintf(parser, "At line no : %d statements : statements statement\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[-1].var -> getName() + "\n" + yyvsp[0].var -> getName());

	fprintf(parser, "%s \n%s\n\n", yyvsp[-1].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 30:
#line 499 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : var_declaration\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[0].var -> getName());

	fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 31:
#line 508 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : expression_statement\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[0].var -> getName());

	fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 32:
#line 517 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : compound_statement\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[0].var -> getName());

	fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
	
;
    break;}
case 33:
#line 526 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : FOR LPAREN expression_statement expression_statement expression RPAREN statement\n\n", lines);
	yyval.var = new SymbolInfo();
	string v = "void ";
	string dec3 = yyvsp[-4].var -> getDeclaration();
	fprintf(parser, "for(%s %s %s)\n%s\n", yyvsp[-4].var -> getName().c_str(), yyvsp[-3].var -> getName().c_str(), yyvsp[-2].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	if(dec3 == v){
		fprintf(errorFile,"Error at Line %d : Invalid declaration of variable\n\n",lines);
		errors++;
	}
	string name3 = yyvsp[-4].var -> getName();
	string name4 = yyvsp[-3].var -> getName();
	string name5 = yyvsp[-2].var -> getName();
	string name7 = yyvsp[0].var -> getName();
	yyval.var -> setName("for(" + name3 + name4 + name5 +")" + "\n" + name7);
;
    break;}
case 34:
#line 542 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : IF LPAREN expression RPAREN statement\n\n", lines);
	yyval.var = new SymbolInfo();
	string v = "void ";
	fprintf(parser, "if(%s)\n %s \n\n", yyvsp[-2].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	if(yyvsp[-2].var -> getDeclaration() == v){
		
		fprintf(errorFile,"Error at Line %d : Invalid declaration of variable\n\n",lines);

		errors++;
	}
	yyval.var -> setName("if(" + yyvsp[-2].var -> getName()+ ")" + "\n" + yyvsp[0].var -> getName());

;
    break;}
case 35:
#line 556 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : IF LPAREN expression RPAREN statement ELSE statement\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "if(%s)\n%s\n else \n %s \n\n", yyvsp[-4].var -> getName().c_str(), yyvsp[-2].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	
	string v = "void ";
	string dec = yyvsp[-4].var -> getDeclaration();

	if(dec == v){
		
		fprintf(errorFile,"Error at Line %d : Invalid declaration of variable\n\n",lines);

		errors++;
	}
	yyval.var -> setName("if(" + yyvsp[-4].var -> getName()+ ")" + "\n" + yyvsp[-2].var -> getName() + "\n" + "else" + "\n" + yyvsp[0].var -> getName());
;
    break;}
case 36:
#line 572 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : WHILE LPAREN expression RPAREN statement\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "while(%s)\n %s \n\n", yyvsp[-2].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	string v = "void ";
	string dec = yyvsp[-2].var -> getDeclaration();
	if(dec == v){
		
		fprintf(errorFile,"Error at Line %d : Invalid declaration of variable\n\n",lines);

		errors++;
	}
	yyval.var -> setName("while(" + yyvsp[-2].var -> getName()+ ")" + "\n" + yyvsp[0].var -> getName());
;
    break;}
case 37:
#line 586 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : PRINTLN LPAREN ID RPAREN SEMICOLON\n\n", lines);
	yyval.var = new SymbolInfo();
	
	yyval.var -> setName("\n(" + yyvsp[-2].var -> getName()+ ")" + ";");

	fprintf(parser, "\n (%s); \n\n", yyvsp[-2].var -> getName().c_str());
	
;
    break;}
case 38:
#line 595 "1605106.y"
{
	fprintf(parser, "At line no : %d statement : RETURN expression SEMICOLON\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "return %s;\n\n", yyvsp[-1].var -> getName().c_str());
	string dec2 = yyvsp[-1].var -> getDeclaration();
	string v = "void ";
	string i ="int ";
	if(dec2 == v){

		yyval.var -> setDeclaration(i);

		
		fprintf(errorFile,"Error at Line %d : Invalid declaration of variable\n\n",lines);

		errors++;
		
	}
	yyval.var -> setName("return " + yyvsp[-1].var -> getName()+ ";");
;
    break;}
case 39:
#line 616 "1605106.y"
{
	fprintf(parser, "At line no : %d expression_statement : SEMICOLON\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(";");

	fprintf(parser, ";\n\n");
	
;
    break;}
case 40:
#line 625 "1605106.y"
{
	fprintf(parser, "At line no : %d expression_statement : expression SEMICOLON\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[-1].var -> getName()+ ";");

	fprintf(parser, "%s ;\n\n", yyvsp[-1].var -> getName().c_str());
	
;
    break;}
case 41:
#line 636 "1605106.y"
{
	fprintf(parser, "At line no : %d variable : ID\n\n", lines);

	yyval.var = new SymbolInfo();
	fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
	string variableName = yyvsp[0].var -> getName();
	if(myTable -> lookUp(variableName) != 0){
		yyval.var -> setDeclaration(myTable -> lookUp(yyvsp[0].var -> getName()) -> getDeclaration());
	}
	if(myTable -> lookUp(yyvsp[0].var -> getName()) == 0){
		
		fprintf(errorFile,"Error at Line %d : Undeclared variable: %s\n\n",lines, yyvsp[0].var -> getName().c_str());
		
		errors++;
		}
	/*else if(myTable -> lookUp($<var>1 -> getName())-> getDeclaration() == "float array" || myTable -> lookUp($<var>1 -> getName())-> getDeclaration() == "int array" ){
		
		fprintf(errorFile,"Error at Line %d : %s is not an array\n\n",lines, $<var>1 -> getName().c_str());
		
		errors++;
		}*/
	


	yyval.var -> setName(yyvsp[0].var -> getName());


;
    break;}
case 42:
#line 664 "1605106.y"
{


	fprintf(parser, "At line no : %d variable : ID LTHIRD expression RTHIRD\n\n", lines);

	yyval.var = new SymbolInfo();

	string dec = yyvsp[-1].var -> getDeclaration();
	string v = "void ";
	string f = "float ";
	string fa = "float array";
	string ia = "int array";
	string i = "int ";

	fprintf(parser, "%s[%s]\n\n", yyvsp[-3].var -> getName().c_str(), yyvsp[-1].var -> getName().c_str());
	if(dec == v || dec == f) {
		
		fprintf(errorFile,"Error at Line %d : Non-integer Array Index  \n\n",lines);

		errors++;
	}
	if(myTable -> lookUp(yyvsp[-3].var -> getName())==0){
		
		fprintf(errorFile,"Error at Line %d : Undeclared variable : %s \n\n",lines, yyvsp[-3].var -> getName().c_str());
		
		errors++;
	}

	if(myTable -> lookUp(yyvsp[-3].var -> getName()) != 0){
		if(myTable -> lookUp(yyvsp[-3].var -> getName()) -> getDeclaration() == fa) 
			yyvsp[-3].var -> setDeclaration(f);
		if(myTable -> lookUp(yyvsp[-3].var -> getName()) -> getDeclaration() != fa && myTable -> lookUp(yyvsp[-3].var -> getName()) -> getDeclaration() != ia){
			//cout << "Line No : "<< lines << " " << $<var>1 -> getName() << "  " << myTable -> lookUp($<var>1 -> getName()) -> getDeclaration() << endl;
			fprintf(errorFile,"Error at Line %d : Type Mismatch \n\n",lines);
			errors++;
		}
		string name1 = yyvsp[-3].var -> getName();
		string dec1 = yyvsp[-3].var -> getDeclaration();
		if(myTable -> lookUp(name1) -> getDeclaration() == ia) 
			yyvsp[-3].var -> setDeclaration(i);	
		yyval.var -> setDeclaration(dec1);
	}
	string n1 = yyvsp[-3].var -> getName();
	string n3 = yyvsp[-1].var -> getName();
	yyval.var -> setName(n1 + "[" + n3 + "]");

;
    break;}
case 43:
#line 713 "1605106.y"
{
	fprintf(parser, "At line no : %d expression : logic_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	string name1 = yyvsp[0].var -> getName();
	yyval.var -> setName(name1);
	string dec1 = yyvsp[0].var -> getDeclaration();
	fprintf(parser, "%s\n\n", yyvsp[0].var -> getName().c_str());
	yyval.var -> setDeclaration(dec1);
;
    break;}
case 44:
#line 722 "1605106.y"
{
	fprintf(parser, "At line no : %d expression : variable ASSIGNOP logic_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "%s=%s\n\n", yyvsp[-2].var -> getName().c_str(), yyvsp[0].var -> getName().c_str());
	string v = "void ";
	string i = "int ";
	string dec3 = yyvsp[0].var -> getDeclaration();
	string n1 = yyvsp[-2].var -> getName();
	string n3 = yyvsp[0].var -> getName();
	string dec1 = yyvsp[-2].var -> getDeclaration();

	if(dec3 == v){
		yyval.var -> setDeclaration(i);
		
		fprintf(errorFile,"Error at Line %d : Invalid declaration of variable\n\n",lines);
		
		errors++;
		
	}
	else if(myTable -> lookUp(n1) != 0){
		if(myTable -> lookUp(n1)-> getDeclaration() != dec3){
			
			fprintf(errorFile,"Error at Line %d : Type Mismatch\n\n",lines);

			errors++;
		}
	}
	yyval.var -> setName(n1+"=" + n3);
	yyval.var -> setDeclaration(dec1);
;
    break;}
case 45:
#line 754 "1605106.y"
{
	fprintf(parser, "At line no : %d logic_expression : rel_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	string dec1 = yyvsp[0].var ->getDeclaration();
	string n1 = yyvsp[0].var -> getName();
	yyval.var -> setDeclaration(dec1);
	fprintf(parser, "%s\n\n", yyvsp[0].var->getName().c_str());
	yyval.var -> setName(n1);

;
    break;}
case 46:
#line 764 "1605106.y"
{
	fprintf(parser, "At line no : %d logic_expression : rel_expression LOGICOP rel_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	string i = "int ";
	string v = "void ";
	string dec1 = yyvsp[-2].var->getDeclaration();
	string dec3 = yyvsp[0].var->getDeclaration();
	fprintf(parser, "%s%s%s\n\n", yyvsp[-2].var->getName().c_str(), yyvsp[-1].var->getName().c_str(), yyvsp[0].var->getName().c_str());
	if(dec1 == v || dec3 == v) {
		
		fprintf(errorFile,"Error at Line %d : Type Mismatch\n\n",lines);

		errors++;
	}
	yyval.var -> setDeclaration(i);
	string n1 = yyvsp[-2].var -> getName();
	string n2 = yyvsp[-1].var -> getName();
	string n3 = yyvsp[0].var -> getName();
	yyval.var -> setName(n1 + n2 + n3);
;
    break;}
case 47:
#line 786 "1605106.y"
{
	fprintf(parser, "At line no : %d rel_expression : simple_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	string n1 = yyvsp[0].var -> getName();
	string dec1 = yyvsp[0].var ->getDeclaration();
	yyval.var -> setDeclaration(dec1);
	fprintf(parser, "%s\n\n", yyvsp[0].var->getName().c_str());
	yyval.var -> setName(n1)
;
    break;}
case 48:
#line 795 "1605106.y"
{
	fprintf(parser, "At line no : %d rel_expression : simple_expression RELOP simple_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	string v = "void ";
	string i = "int ";
	string dec1 = yyvsp[-2].var->getDeclaration();
	string dec3 = yyvsp[0].var->getDeclaration();
	fprintf(parser, "%s%s%s\n\n", yyvsp[-2].var->getName().c_str(), yyvsp[-1].var->getName().c_str(), yyvsp[0].var->getName().c_str());
	if(dec1 == v || dec3 == v) {
		
		fprintf(errorFile,"Error at Line %d : Type Mismatch\n\n",lines);

		errors++;
	}
	yyval.var -> setDeclaration(i);
	yyval.var -> setName(yyvsp[-2].var -> getName()+ yyvsp[-1].var->getName()+ yyvsp[0].var->getName().c_str());
;
    break;}
case 49:
#line 814 "1605106.y"
{
	fprintf(parser, "At line no : %d simple_expression : term\n\n", lines);
	yyval.var = new SymbolInfo();

	yyval.var -> setName(yyvsp[0].var -> getName());
	
	yyval.var -> setDeclaration(yyvsp[0].var ->getDeclaration());

	fprintf(parser, "%s\n\n", yyvsp[0].var->getName().c_str());
;
    break;}
case 50:
#line 824 "1605106.y"
{
	fprintf(parser, "At line no : %d simple_expression : simple_expression ADDOP term\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "%s%s%s\n\n", yyvsp[-2].var->getName().c_str(), yyvsp[-1].var->getName().c_str(), yyvsp[0].var->getName().c_str());
	string f = "float ";
	string v = "void ";
	string i = "int ";
	if(yyvsp[0].var->getDeclaration() == f || yyvsp[-2].var->getDeclaration() == f ) {
		yyval.var -> setDeclaration(f);
	}
	else if(yyvsp[0].var->getDeclaration() == v || yyvsp[-2].var->getDeclaration() == v) {
		yyval.var -> setDeclaration(i);
		fprintf(errorFile,"Error at Line %d : Type Mismatch\n\n",lines);
		

		errors++;
	}
	else yyval.var -> setDeclaration(i);
	yyval.var -> setName(yyvsp[-2].var -> getName()+ yyvsp[-1].var->getName()+ yyvsp[0].var->getName().c_str());
;
    break;}
case 51:
#line 846 "1605106.y"
{
	fprintf(parser, "At line no : %d term : unary_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	string dec = yyvsp[0].var ->getDeclaration();
	string name1 = yyvsp[0].var -> getName();
	yyval.var -> setName(name1);
	fprintf(parser, "%s\n\n", yyvsp[0].var->getName().c_str());
	yyval.var -> setDeclaration(dec);
	
;
    break;}
case 52:
#line 856 "1605106.y"
{
	fprintf(parser, "At line no : %d term : term MULOP unary_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	string v = "void ";
	string i = "int ";
	string f = "float ";
	string dec1 = yyvsp[-2].var->getDeclaration();
	string dec3 = yyvsp[0].var->getDeclaration();
	fprintf(parser, "%s%s%s\n\n", yyvsp[-2].var->getName().c_str(), yyvsp[-1].var->getName().c_str(), yyvsp[0].var->getName().c_str());
	if(dec1 == v || dec3 == v) {
		yyval.var -> setDeclaration(i);
		fprintf(errorFile,"Error at Line %d : Type Mismatch\n\n",lines);
		errors++;
	}
	else if(yyvsp[-1].var -> getName() == "/"){
		if(dec1 == i && dec3 == i)
			yyval.var -> setDeclaration(i);
		else if(dec1 == v || dec3 == v){
			yyval.var -> setDeclaration(i);
			fprintf(errorFile, "Error at Line %d : Type Mismatch\n\n", lines);
			errors++;
		}
		else yyval.var -> setDeclaration(f);
	}
	else if(yyvsp[-1].var -> getName() == "%"){
		if(dec1 != i || dec3 != i) {
			
			fprintf(errorFile,"Error at Line %d : Integer operand on modulus operator\n\n",lines);

			errors++;
		}
		yyval.var -> setDeclaration(i);
	}
	else {
		if(dec1 == f || dec3 == f)
			yyval.var -> setDeclaration(f);
		else if(dec1 == v || dec3 == v){
			yyval.var -> setDeclaration(i);
			fprintf(errorFile, "Error at Line %d : Type Mismatch\n\n", lines);
			errors++;
		}
		else yyval.var -> setDeclaration(i);
	}
	string str1 = yyvsp[-2].var -> getName();
	string str2 = yyvsp[-1].var->getName();
	string str3 = yyvsp[0].var->getName();
	string name =  yyvsp[-2].var -> getName() + yyvsp[-1].var->getName() + yyvsp[0].var->getName();
	yyval.var -> setName(name);
;
    break;}
case 53:
#line 907 "1605106.y"
{
	fprintf(parser, "At line no : %d unary_expression : ADDOP unary_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	string v = "void ";
	string i = "int ";
	string f = "float ";
	string dec2 = yyvsp[0].var -> getDeclaration();

	fprintf(parser, "%s%s\n\n", yyvsp[-1].var->getName().c_str(), yyvsp[0].var->getName().c_str());
	if(dec2 == v){
		
		yyval.var -> setDeclaration(i);
		
		fprintf(errorFile,"Error at Line %d : Type Mismatch\n\n",lines);

		errors++;
		
	}
	else {
		string dec2 = yyvsp[0].var -> getDeclaration();
		yyval.var -> setDeclaration(dec2);
	}
	string str1 = yyvsp[-1].var -> getName();
	string str2 = yyvsp[0].var -> getName();
	yyval.var -> setName(str1+ str2);

;
    break;}
case 54:
#line 934 "1605106.y"
{
	fprintf(parser, "At line no : %d unary_expression : NOT unary_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "!%s\n\n",yyvsp[0].var->getName().c_str());

	string v = "void ";
	string i = "int ";
	string dec2 = yyvsp[0].var -> getDeclaration();
	string n2 = yyvsp[0].var->getName();
	if(dec2 == v){
		yyval.var -> setDeclaration(i);

		
		fprintf(errorFile,"Error at Line %d : Type Mismatch\n\n",lines);

		errors++;
		
	}
	else {
		yyval.var -> setDeclaration(dec2);
	}
	yyval.var -> setName("!"+ n2);
;
    break;}
case 55:
#line 957 "1605106.y"
{
	fprintf(parser, "At line no : %d unary_expression : factor\n\n", lines);
	yyval.var = new SymbolInfo();
	string var1 = yyvsp[0].var->getName();
	yyval.var -> setName(var1);
	fprintf(parser, "%s\n\n",yyvsp[0].var->getName().c_str());
	string dec1 = yyvsp[0].var -> getDeclaration();
	yyval.var -> setDeclaration(dec1);
;
    break;}
case 56:
#line 967 "1605106.y"
{
	fprintf(parser, "At line no : %d factor : variable\n\n", lines);
	yyval.var = new SymbolInfo();
	string var1 = yyvsp[0].var->getName();
	yyval.var -> setName(var1);
	fprintf(parser, "%s\n\n",yyvsp[0].var->getName().c_str());
	string dec1 = yyvsp[0].var -> getDeclaration();
	yyval.var -> setDeclaration(dec1);
;
    break;}
case 57:
#line 976 "1605106.y"
{
	fprintf(parser, "At line no : %d factor : ID LPAREN argument_list RPAREN\n\n", lines);
	yyval.var = new SymbolInfo();
	string i = "int ";
	fprintf(parser, "%s(%s)\n\n",yyvsp[-3].var->getName().c_str(), yyvsp[-1].var->getName().c_str());
	string variableName = yyvsp[-3].var->getName();
	SymbolInfo *temp = myTable -> lookUp(variableName);
	//cout << $<var>1->getName()<< endl;
	//cout << temp->getFunction() -> getTotalParameters() << endl;
	if(temp == 0){
		yyval.var->setDeclaration(i);
		fprintf(errorFile,"Error at Line %d : Undeclared function\n\n",lines);
		errors++;
	}
	else if(temp -> getFunction() == 0){
		yyval.var->setDeclaration(i);
		fprintf(errorFile,"Error at Line %d : Not a function\n\n",lines);
		errors++;
		
	}
	else{
		int p = temp -> getFunction() -> getTotalParameters();
		bool def = temp -> getFunction() -> getDefined();
		if(def == 0){
			fprintf(errorFile,"Error at Line %d : Undeclared function\n\n",lines);
			errors++;
		}
		yyval.var -> setDeclaration(temp -> getFunction() -> getRType());
		
		if(p != arguments.size()){
			//cout << lines << " " <<p <<endl;
			//cout << lines << " " <<arguments.size() <<endl;
			fprintf(errorFile,"Error at Line %d : Invalid number of arguments\n\n",lines);
			errors++;
		}
		else{
			vector<string> pt = temp -> getFunction() -> getParameterType();
			int argSize = arguments.size();
			for(int i=0; i < argSize; i++){
				if(arguments[i]->getDeclaration()!=pt[i]){
					fprintf(errorFile,"Error at Line %d : Type Mismatch\n\n",lines);
					errors++;
					break;
				}
			}
		}
	}
	arguments.clear();
	yyval.var -> setName(yyvsp[-3].var->getName()+ "(" + yyvsp[-1].var->getName() + ")");
;
    break;}
case 58:
#line 1026 "1605106.y"
{
	fprintf(parser, "At line no : %d factor : LPAREN expression RPAREN\n\n", lines);
	yyval.var = new SymbolInfo();
	string var2 = "("+ yyvsp[-1].var->getName()+")";
	yyval.var -> setName(var2);
	fprintf(parser, "(%s)\n\n",yyvsp[-1].var->getName().c_str());
	string dec2 = yyvsp[-1].var -> getDeclaration();
	yyval.var -> setDeclaration(dec2);
;
    break;}
case 59:
#line 1035 "1605106.y"
{
	fprintf(parser, "At line no : %d factor : CONST_INT\n\n", lines);
	yyval.var = new SymbolInfo();
	string i = "int ";
	string var1 = yyvsp[0].var->getName();
	yyval.var -> setName(var1);
	fprintf(parser, "%s\n\n",yyvsp[0].var->getName().c_str());
	yyval.var -> setDeclaration(i);
;
    break;}
case 60:
#line 1044 "1605106.y"
{
	fprintf(parser, "At line no : %d factor : CONST_FLOAT\n\n", lines);
	yyval.var = new SymbolInfo();
	string f = "float ";
	string var1 = yyvsp[0].var->getName();
	yyval.var -> setName(var1);
	fprintf(parser, "%s\n\n",yyvsp[0].var->getName().c_str());
	yyval.var -> setDeclaration(f);
;
    break;}
case 61:
#line 1053 "1605106.y"
{
	fprintf(parser, "At line no : %d factor : variable INCOP\n\n", lines);
	yyval.var = new SymbolInfo();	
	string var1 = yyvsp[-1].var->getName() + "++";
	yyval.var -> setName(var1);
	fprintf(parser, "%s\n\n",yyvsp[-1].var->getName().c_str());
	string dec1 = yyvsp[-1].var -> getDeclaration();
	yyval.var -> setDeclaration(dec1);
;
    break;}
case 62:
#line 1062 "1605106.y"
{
	fprintf(parser, "At line no : %d factor : variable DECOP\n\n", lines);
	yyval.var = new SymbolInfo();
	string var1 = yyvsp[-1].var->getName()+"--";
	yyval.var -> setName(var1);
	fprintf(parser, "%s\n\n",yyvsp[-1].var->getName().c_str());
	string dec1 = yyvsp[-1].var -> getDeclaration();
	yyval.var -> setDeclaration(dec1);
;
    break;}
case 63:
#line 1074 "1605106.y"
{
	fprintf(parser, "At line no : %d argument_list : arguments\n\n", lines);
	yyval.var = new SymbolInfo();
	string var1 = yyvsp[0].var->getName();
	yyval.var -> setName(var1);
	fprintf(parser, "%s\n\n",yyvsp[0].var->getName().c_str());
;
    break;}
case 64:
#line 1081 "1605106.y"
{
	fprintf(parser, "At line no : %d argument_list : \n\n", lines);
	yyval.var = new SymbolInfo();
	yyval.var -> setName("");
;
    break;}
case 65:
#line 1088 "1605106.y"
{
	fprintf(parser, "At line no : %d arguments : arguments COMMA logic_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "%s,%s\n\n",yyvsp[-2].var->getName().c_str(), yyvsp[0].var->getName().c_str());
	arguments.push_back(yyvsp[0].var);
	string setter = yyvsp[-2].var->getName()+ "," + yyvsp[0].var->getName();
	yyval.var -> setName(setter);
;
    break;}
case 66:
#line 1096 "1605106.y"
{
	fprintf(parser, "At line no : %d arguments : logic_expression\n\n", lines);
	yyval.var = new SymbolInfo();
	fprintf(parser, "%s\n\n",yyvsp[0].var->getName().c_str());
	string n1 = yyvsp[0].var->getName();
	string type1 = yyvsp[0].var->getType();
	string dec1 = yyvsp[0].var->getDeclaration();
	yyval.var -> setName(n1);
	arguments.push_back(new SymbolInfo(n1, type1, dec1));
;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 1107 "1605106.y"


int main(int argc,char *argv[])
{
	if((fp=fopen(argv[1],"r"))==NULL){
		printf("Cannot Open Input File.\n"); exit(1);}
	yyin=fp;
	myTable -> enterScope(7);
	yyparse();
	fprintf(parser, "Total lines : %d\n",lines);
	fprintf(errorFile, "Total errors : %d", errors);
	fprintf(parser, "Total errors : %d", errors);
	fclose(fp);
	fclose(parser);
	fclose(errorFile);
	return 0;
}
